export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_CHANGE = 'AUTH_CHANGE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const DESELECT_MOVIE = 'DESELECT_MOVIE';
export const YOUTUBE_SEARCH_MOVIE = 'YOUTUBE_SEARCH_MOVIE';
export const SELECT_MOVIE_TIME = 'SELECT_MOVIE_TIME';
export const DESELECT_MOVIE_TIME = 'DESELECT_MOVIE_TIME';

export const SELECT_SEAT = 'SELECT_SEAT';
export const DESELECT_SEAT = 'DESELECT_SEAT';
