export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_CHANGE = 'AUTH_CHANGE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const DESELECT_MOVIE = 'DESELECT_MOVIE';
export const YOUTUBE_SEARCH_MOVIE = 'YOUTUBE_SEARCH_MOVIE';
export const SELECT_MOVIE_TIME = 'SELECT_MOVIE_TIME';
export const DESELECT_MOVIE_TIME = 'DESELECT_MOVIE_TIME';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';

export const SELECT_SEAT = 'SELECT_SEAT';
export const DESELECT_SEAT = 'DESELECT_SEAT';
export const CLEAR_SEATS = 'CLEAR_SEATS';

export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const CLEAR_ALL_PURCHASES = 'CLEAR_ALL_PURCHASES';

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const CLEAR_ORDER_HISTORY = 'CLEAR_ORDER_HISTORY';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const TOGGLE_ACCOUNT_DETAILS = 'TOGGLE_ACCOUNT_DETAILS';

export const ADD_ADDON = 'ADD_ADDON';
export const REMOVE_ADDON = 'REMOVE_ADDON';
export const CLEAR_ALL_ADDONS = 'CLEAR_ALL_ADDONS';

export const PROCESS_PAYMENT_START = 'PROCESS_PAYMENT_START';
export const PROCESS_PAYMENT_SUCCESS = 'PROCESS_PAYMENT_SUCCESS';
export const PROCESS_PAYMENT_FAIL = 'PROCESS_PAYMENT_START';
export const UPDATE_PAYMENT_STATUS_SUCCESS = 'UPDATE_PAYMENT_STATUS_SUCCESS';
export const UPDATE_PAYMENT_STATUS_FAIL = 'UPDATE_PAYMENT_STATUS_FAIL';
export const CLEAR_PAYMENT_STATUS = 'CLEAR_PAYMENT_STATUS';
